import Head from "next/head";
import About from "../components/About";
import Main from "../components/Main";
import Navbar from "../sections/Navbar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Yixin | Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Main />
      <About />
    </div>
  );
};

export default Home;
